import type { HtProduct, HtRelatedProduct, HtRegion } from './types'

export const region: HtRegion = {
  id: 'reg_cn',
  name: 'China / Export',
  currency_code: 'cny',
}

export const product: HtProduct = {
  id: 'prod_ce8523',
  handle: 'homtree-ce8523-roll-cake-emulsifier',
  title: 'Homtree CE8523 Roll Cake Emulsifier',
  subtitle: 'Компаунд-эмульгатор для рулетов, слоёных тортов и гибких бисквитных пластов',
  description:
    'Компаунд-эмульгатор для рулетных бисквитов. Даёт глянцевую поверхность, эластичность и стабильную скручиваемость без трещин, сохраняет мягкую и влажную структуру мякиша на всём сроке годности.',
  collection: { id: 'pcol_cake', title: 'Решения для тортов и бисквитов' },
  images: [
    {
      id: 'img_1',
      url: '/products/ce8523-pail.png',
      alt: 'Ведро Homtree CE8523 на 5 кг',
    },
    {
      id: 'img_2',
      url: '/products/ce8523-carton.png',
      alt: 'Экспортная фасовка Homtree CE8523: мешок 25 кг и картон',
    },
    {
      id: 'img_3',
      url: '/products/ce8523-application.png',
      alt: 'Применение: рулетный бисквит с ровной структурой мякиша',
    },
  ],
  variants: [
    {
      id: 'variant_01',
      title: 'Standard · 5 kg pail',
      sku: 'HT-CE8523-01',
      options: [
        { option_title: 'Grade', value: 'Standard' },
        { option_title: 'Фасовка', value: '5 kg pail' },
        { option_title: 'Применение', value: 'Roll Cake' },
      ],
      metadata: {
        net_weight_kg: 5,
        gross_weight_kg: 5.4,
        volume_m3: 0.009,
        units_per_pallet: 96,
        lead_time_days: 7,
        grade: 'Standard',
        packaging: '5 kg pail',
      },
      inventory_quantity: 1840,
      manage_inventory: true,
      allow_backorder: false,
      inventory_state: 'in_stock',
      calculated_price: {
        calculated_amount: 37000,
        original_amount: 37000,
        currency_code: 'cny',
        price_list_id: null,
        price_list_type: null,
      },
      price_tiers: [
        { min_quantity: 1, max_quantity: 19, amount: 37000, discount_percent: 0 },
        { min_quantity: 20, max_quantity: 99, amount: 35150, discount_percent: 5 },
        { min_quantity: 100, max_quantity: null, amount: 33300, discount_percent: 10 },
      ],
      min_order_quantity: 5,
      order_step: 1,
    },
    {
      id: 'variant_02',
      title: 'Premium · 20 kg pail',
      sku: 'HT-CE8523-02',
      options: [
        { option_title: 'Grade', value: 'Premium' },
        { option_title: 'Фасовка', value: '20 kg pail' },
        { option_title: 'Применение', value: 'Layer Cake' },
      ],
      metadata: {
        net_weight_kg: 20,
        gross_weight_kg: 21.2,
        volume_m3: 0.034,
        units_per_pallet: 32,
        lead_time_days: 10,
        grade: 'Premium',
        packaging: '20 kg pail',
      },
      inventory_quantity: 240,
      manage_inventory: true,
      allow_backorder: true,
      inventory_state: 'in_stock',
      calculated_price: {
        calculated_amount: 138000,
        original_amount: 138000,
        currency_code: 'cny',
        price_list_id: null,
        price_list_type: null,
      },
      price_tiers: [
        { min_quantity: 1, max_quantity: 9, amount: 138000, discount_percent: 0 },
        { min_quantity: 10, max_quantity: 39, amount: 131100, discount_percent: 5 },
        { min_quantity: 40, max_quantity: null, amount: 124200, discount_percent: 10 },
      ],
      min_order_quantity: 2,
      order_step: 1,
    },
    {
      id: 'variant_03',
      title: 'Export · 25 kg carton',
      sku: 'HT-CE8523-03',
      options: [
        { option_title: 'Grade', value: 'Export' },
        { option_title: 'Фасовка', value: '25 kg carton' },
        { option_title: 'Применение', value: 'Cake Sheet' },
      ],
      metadata: {
        net_weight_kg: 25,
        gross_weight_kg: 26,
        volume_m3: 0.035,
        units_per_pallet: 24,
        lead_time_days: 14,
        grade: 'Export',
        packaging: '25 kg carton',
      },
      inventory_quantity: 0,
      manage_inventory: true,
      allow_backorder: true,
      inventory_state: 'made_to_order',
      calculated_price: {
        calculated_amount: 165000,
        original_amount: 165000,
        currency_code: 'cny',
        price_list_id: null,
        price_list_type: null,
      },
      price_tiers: [
        { min_quantity: 1, max_quantity: 7, amount: 165000, discount_percent: 0 },
        { min_quantity: 8, max_quantity: 23, amount: 155100, discount_percent: 6 },
        { min_quantity: 24, max_quantity: null, amount: 145200, discount_percent: 12 },
      ],
      min_order_quantity: 1,
      order_step: 1,
    },
  ],
  metadata: {
    application: 'Рулеты, слоёные торты и гибкие бисквитные пласты.',
    commercial_terms:
      'Каталожная цена в CNY. Финальные условия по России/СНГ, логистика, скидки, сертификаты и инвойс-пакет подтверждаются котировкой менеджера.',
    hs_code: '3824.99',
    origin_country: 'CN',
    shelf_life: '12 месяцев',
    factory: 'Homtree · Zhejiang',
  },
  spec_groups: [
    {
      label: 'Технологические параметры',
      rows: [
        { label: 'Дозировка', value: '4–6% на массу муки' },
        { label: 'Форма', value: 'Паста, гидратированный гель' },
        { label: 'Растворимость', value: 'Полная в водной фазе' },
        { label: 'Температура ввода', value: '18–26 °C' },
        { label: 'pH готовой смеси', value: '5.8–6.6' },
      ],
    },
    {
      label: 'Состав и соответствие',
      rows: [
        { label: 'Основные компоненты', value: 'E471, E475, E477, сорбит' },
        { label: 'Аллергены', value: 'Не содержит' },
        { label: 'ГМО', value: 'Не содержит' },
        { label: 'Halal / Kosher', value: 'Сертифицировано' },
        { label: 'HS-код', value: '3824.99' },
      ],
    },
    {
      label: 'Хранение и логистика',
      rows: [
        { label: 'Срок годности', value: '12 месяцев' },
        { label: 'Условия хранения', value: '5–25 °C, без прямого солнца' },
        { label: 'Страна происхождения', value: 'Китай' },
        { label: 'Производство', value: 'Homtree · Zhejiang' },
        { label: 'Транспортировка', value: 'Обычный контейнер, без реф-режима' },
      ],
    },
  ],
  documents: [
    { id: 'doc_tds', title: 'Technical Data Sheet · CE8523', kind: 'tds', size: 'PDF · 420 КБ' },
    { id: 'doc_coa', title: 'Certificate of Analysis (партия)', kind: 'coa', size: 'PDF · 180 КБ' },
    { id: 'doc_halal', title: 'Halal Certificate', kind: 'certificate', size: 'PDF · 310 КБ' },
    { id: 'doc_decl', title: 'Декларация ТР ТС 029/2012', kind: 'declaration', size: 'PDF · 260 КБ' },
  ],
  case_studies: [
    {
      id: 'case_1',
      rating: 5,
      title: 'Продлили свежесть нарезного тоста до 7 дней',
      author: 'АО «Хлебокомбинат №3»',
      role: 'Главный технолог',
      body: 'Перешли на улучшитель M102 для линейки пшеничных тостов. Основная задача была убрать крошковатость мякиша на 4–5 день хранения. Тестовые выпечки показали, что структура остаётся эластичной и мягкой на протяжении полных 7 суток без изменения вкусового профиля. Клейковина муки у нас нестабильная, но данный компонент полностью нивелирует перепады качества сырья. Планируем заказать Custom Formula в мешках по 25 кг под наши индустриальные линии.',
    },
    {
      id: 'case_2',
      rating: 4.8,
      title: 'Реальный расход ниже базовых аналогов',
      author: 'Сеть пекарен «Хлебный Дом»',
      role: 'Зав. производством',
      body: 'Считали расход на тонну готовой продукции. При дозировке 4% получили тот же объём и структуру, что на европейском аналоге при 6%. За квартал экономия по позиции составила около 14% при неизменной рецептуре и режимах выпечки.',
    },
    {
      id: 'case_3',
      rating: 5,
      title: 'Подходит для частичной выпечки (Part-baked)',
      author: 'Крафтовое производство BakerTrade',
      role: 'Технолог',
      body: 'Тестировали на линии part-baked с последующей заморозкой. После дефростации и досдачи в печь бисквитный пласт не рвётся при скручивании, поверхность остаётся глянцевой. Для нас критично, что не требуется менять цикл заморозки.',
    },
  ],
}

export const relatedProducts: HtRelatedProduct[] = [
  {
    id: 'prod_ce8503',
    handle: 'homtree-ce8503-sp-cake-gel-emulsifier',
    sku: 'HT-CE8503-01',
    title: 'Homtree CE8503 SP Cake Gel Emulsifier',
    image: null,
    amount: 36000,
    moq: 'MOQ 25 кг',
    packaging: 'Ведро 5 кг',
    inventory_state: 'in_stock',
  },
  {
    id: 'prod_jam_blueberry',
    handle: 'homtree-blueberry-fruit-filling',
    sku: 'HT-JAM-BLUEBERRY-01',
    title: 'Homtree Blueberry Fruit Filling',
    image: '/products/ce8523-application.png',
    amount: 6200,
    moq: 'MOQ 25 кг',
    packaging: 'Ведро 20 кг',
    inventory_state: 'in_stock',
  },
  {
    id: 'prod_fd703',
    handle: 'homtree-ce-fd703-frozen-cake-stabilizer',
    sku: 'HT-CE-FD703-01',
    title: 'Homtree CE FD703 Frozen Cake Stabilizer',
    image: null,
    amount: 56000,
    moq: 'MOQ 25 кг',
    packaging: 'Мешок 25 кг',
    inventory_state: 'on_request',
  },
  {
    id: 'prod_ce9222',
    handle: 'homtree-ce9222-waffle-cake-emulsifier',
    sku: 'HT-CE9222-01',
    title: 'Homtree CE9222 Waffle Cake Emulsifier',
    image: null,
    amount: 35000,
    moq: 'MOQ 25 кг',
    packaging: 'Ведро 5 кг',
    inventory_state: 'in_stock',
  },
  {
    id: 'prod_dl2020',
    handle: 'homtree-dl2020-clean-label-cake-gel',
    sku: 'HT-DL2020-01',
    title: 'Homtree DL2020 Clean Label Cake Gel',
    image: null,
    amount: 43000,
    moq: 'MOQ 25 кг',
    packaging: 'Ведро 20 кг',
    inventory_state: 'in_stock',
  },
  {
    id: 'prod_so600',
    handle: 'homtree-so600-pre-emulsified-bakery-oil',
    sku: 'HT-SO600-01',
    title: 'Homtree SO600 Pre-Emulsified Bakery Oil',
    image: null,
    amount: 78000,
    moq: 'MOQ 25 кг',
    packaging: 'Мешок 25 кг',
    inventory_state: 'made_to_order',
  },
  {
    id: 'prod_fd100',
    handle: 'homtree-m-fd100-frozen-dough-enzyme',
    sku: 'HT-M-FD100-01',
    title: 'Homtree M FD100 Frozen Dough Enzyme',
    image: '/products/ce8523-pail.png',
    amount: 28000,
    moq: 'MOQ 25 кг',
    packaging: 'Ведро 5 кг',
    inventory_state: 'in_stock',
  },
  {
    id: 'prod_m101',
    handle: 'homtree-m101-bread-enzyme-improver',
    sku: 'HT-M101-01',
    title: 'Homtree M101 Bread Enzyme Improver',
    image: '/products/ce8523-carton.png',
    amount: 18500,
    moq: 'MOQ 25 кг',
    packaging: 'Мешок 25 кг',
    inventory_state: 'in_stock',
  },
]
